import { useState } from 'react'
import { scaleQuantity } from '../lib/quantity'
import { Pill } from './ui'

export default function RecipeBody({ recipe }) {
  const baseServings = recipe.servings || null
  const [servings, setServings] = useState(baseServings)
  const scale = baseServings && servings ? servings / baseServings : 1
  const scaled = scale !== 1

  return (
    <article className="space-y-14">
      {/* === Headline block === */}
      <header className="rise">
        <div className="flex items-center gap-4 mb-6">
          <span className="font-display italic text-ink-muted tnum">№001</span>
          <span className="eyebrow">Today's recipe</span>
          <span className="flex-1 h-px bg-rule" />
        </div>

        <h1 className="display-xl">{renderTitle(recipe.title)}</h1>

        {recipe.summary && (
          <p className="font-display text-xl sm:text-2xl leading-snug text-ink-soft mt-6 max-w-3xl">
            {recipe.summary}
          </p>
        )}

        <div className="flex flex-wrap items-center gap-3 mt-7">
          {recipe.servings != null && (
            <Pill>
              🍽 {recipe.servings} {recipe.servings === 1 ? 'serving' : 'servings'}
            </Pill>
          )}
          {recipe.total_time_min != null && (
            <Pill>⏱ {recipe.total_time_min} min</Pill>
          )}
          {recipe.cuisine && (
            <Pill tone="sage" className="capitalize">
              {recipe.cuisine}
            </Pill>
          )}
          {recipe.kcal_per_serving != null && (
            <Pill
              tone="accent"
              title="Estimated kilocalories per serving — generated by AI from the ingredient list, treat as a rough approximation."
            >
              🔥 ≈ {recipe.kcal_per_serving} kcal / serving
            </Pill>
          )}
          {recipe.cost_usd != null && (
            <Pill tone="saffron" title={costTooltip(recipe)}>
              ≈ {formatCost(recipe.cost_usd)}
            </Pill>
          )}
        </div>

        {recipe.source_url && (
          <a
            href={recipe.source_url}
            target="_blank"
            rel="noreferrer"
            className="link-grow inline-flex items-center gap-2 mt-6 text-sm text-terracotta tracking-wide"
          >
            Source video ↗
          </a>
        )}
      </header>

      {/* === Ingredients ↔ Steps spread === */}
      <div className="grid grid-cols-12 gap-x-6 lg:gap-x-12 gap-y-12">
        {/* Left rail — ingredients */}
        <section className="col-span-12 lg:col-span-5 lg:sticky lg:top-24 lg:self-start">
          <div className="flex items-baseline justify-between mb-5">
            <h2 className="display-md">
              <span className="italic" style={{ fontVariationSettings: '"opsz" 60, "SOFT" 100' }}>
                Ingredients
              </span>
            </h2>
            {baseServings != null && (
              <ServingsScaler
                base={baseServings}
                value={servings}
                onChange={setServings}
              />
            )}
          </div>

          <ul className="border-t border-rule">
            {recipe.ingredients.map((ing) => (
              <li
                key={`${ing.position}-${ing.item}`}
                className="grid grid-cols-[7rem_1fr] gap-4 py-3 border-b border-rule-soft"
              >
                <span className="font-display text-ink-muted tnum text-[15px] pt-0.5">
                  {[
                    scaled ? scaleQuantity(ing.quantity, scale) : ing.quantity,
                    ing.unit,
                  ]
                    .filter(Boolean)
                    .join(' ') || '—'}
                </span>
                <span className="text-ink leading-snug">
                  <span className="font-display text-[17px]">{ing.item}</span>
                  {ing.notes && (
                    <span className="block text-sm text-ink-muted italic mt-0.5">
                      {ing.notes}
                    </span>
                  )}
                </span>
              </li>
            ))}
          </ul>
        </section>

        {/* Right column — steps */}
        <section className="col-span-12 lg:col-span-7">
          <h2 className="display-md mb-5">
            <span className="italic" style={{ fontVariationSettings: '"opsz" 60, "SOFT" 100' }}>
              Method
            </span>
          </h2>

          <ol className="space-y-7">
            {recipe.steps.map((s) => (
              <li
                key={`${s.position}`}
                className="grid grid-cols-[3.5rem_1fr] gap-5"
              >
                <span
                  className="font-display italic text-terracotta leading-none tnum"
                  style={{
                    fontSize: '2.6rem',
                    fontVariationSettings: '"opsz" 96, "SOFT" 100',
                    fontWeight: 300,
                  }}
                >
                  {String(s.position + 1).padStart(2, '0')}
                </span>
                <p className="font-display text-[18px] sm:text-[19px] leading-relaxed text-ink pt-1">
                  {s.text}
                </p>
              </li>
            ))}
          </ol>
        </section>
      </div>

      {/* === Tips === */}
      {recipe.tips && recipe.tips.length > 0 && (
        <section className="border-t border-rule pt-10">
          <div className="flex items-baseline gap-4 mb-6">
            <span className="font-display italic text-saffron tnum">aside</span>
            <span className="eyebrow">From the chef</span>
            <span className="flex-1 h-px bg-rule" />
          </div>
          <div className="bg-saffron-soft/50 border border-saffron/20 rounded-2xl p-7 sm:p-9 relative">
            <span
              aria-hidden="true"
              className="absolute -top-3 left-7 bg-paper px-3 font-display italic text-saffron text-sm"
            >
              ❋ Tips
            </span>
            <ul className="space-y-4">
              {recipe.tips.map((tip, i) => (
                <li
                  key={i}
                  className="grid grid-cols-[1.5rem_1fr] gap-3 font-display text-[17px] leading-relaxed text-ink"
                >
                  <span className="text-saffron italic tnum text-sm pt-1">
                    {String(i + 1).padStart(2, '0')}
                  </span>
                  <span>{tip}</span>
                </li>
              ))}
            </ul>
          </div>
        </section>
      )}
    </article>
  )
}

/* Render the title splitting on the last word so we can italicize it for visual rhythm */
function renderTitle(title) {
  if (!title) return null
  const trimmed = title.trim()
  const lastSpace = trimmed.lastIndexOf(' ')
  if (lastSpace === -1 || trimmed.length < 14) return trimmed
  const head = trimmed.slice(0, lastSpace)
  const tail = trimmed.slice(lastSpace + 1)
  return (
    <>
      {head}{' '}
      <span
        className="italic"
        style={{ fontVariationSettings: '"opsz" 144, "SOFT" 100' }}
      >
        {tail}
      </span>
    </>
  )
}

function ServingsScaler({ base, value, onChange }) {
  return (
    <div className="flex items-center gap-3 text-sm">
      <span className="eyebrow">Serves</span>
      <div className="inline-flex items-center bg-paper-soft border border-rule rounded-full">
        <button
          type="button"
          onClick={() => onChange(Math.max(1, value - 1))}
          className="w-9 h-9 flex items-center justify-center text-ink-muted hover:text-ink transition-colors"
          aria-label="Decrease servings"
        >
          −
        </button>
        <span className="px-2 font-display tnum text-base text-ink min-w-[2ch] text-center">
          {value}
        </span>
        <button
          type="button"
          onClick={() => onChange(value + 1)}
          className="w-9 h-9 flex items-center justify-center text-ink-muted hover:text-ink transition-colors"
          aria-label="Increase servings"
        >
          +
        </button>
      </div>
      {value !== base && (
        <button
          type="button"
          onClick={() => onChange(base)}
          className="link-grow text-xs text-terracotta tracking-wide"
        >
          reset
        </button>
      )}
    </div>
  )
}

function formatCost(usd) {
  if (usd < 0.01) return `$${usd.toFixed(4)}`
  if (usd < 1) return `$${usd.toFixed(3)}`
  return `$${usd.toFixed(2)}`
}

function costTooltip(recipe) {
  const parts = []
  if (recipe.llm_model) parts.push(`Model: ${recipe.llm_model}`)
  if (recipe.llm_input_tokens != null)
    parts.push(`Tokens in: ${recipe.llm_input_tokens.toLocaleString()}`)
  if (recipe.llm_output_tokens != null)
    parts.push(`Tokens out: ${recipe.llm_output_tokens.toLocaleString()}`)
  if (recipe.transcribe_seconds != null)
    parts.push(`Audio: ${Math.round(recipe.transcribe_seconds)}s`)
  return parts.join(' · ')
}
